id: 1_Abromics_general_pipeline
type: pipeline
info:
  display_name: Abromics General Pipeline
  category: Edited
  tags:
  - Abromics
  - SOA8_ST2.2
  - SPARMVET
  - STEC
  - Escherichia coli
  description: Manifest for Abromics General Pipeline. SPARMVET. Usable for STEC / E.coli.
  version: '1.0'
data_schemas:
  #Summary: !include '1_Abromics_general_pipeline/Summary.yaml'
  #Detailed_Summary: !include '1_Abromics_general_pipeline/Detailed_Summary.yaml'
  ResFinder: !include '1_Abromics_general_pipeline/ResFinder.yaml'
  #PlasmidFinder: !include '1_Abromics_general_pipeline/PlasmidFinder.yaml'
  #MLST_results: !include '1_Abromics_general_pipeline/MLST_results.yaml'
  #FastP: !include '1_Abromics_general_pipeline/FastP.yaml'
  #Bracken: !include '1_Abromics_general_pipeline/Bracken.yaml'
  #Quast: !include '1_Abromics_general_pipeline/Quast.yaml'
  #Quality_metrics: !include '1_Abromics_general_pipeline/Quality_metrics.yaml'
metadata_schema: !include '1_Abromics_general_pipeline/metadata_schema.yaml'
plot_defaults:
  height: 450
  theme: theme_minimal
  show_legend: true
analysis_groups:
  Example_Group:
    description: Auto-scaffolded plotting group
    plots:
      demo_bar:
        factory_id: bar_logic
        target_dataset: Summary
        target_col: Replace_Me
        title: Replace Me Title
