# SECTION - Manifest description
id: ST22_dummy_manifest
type: species
info:
  display_name: ST22 Dummy Dataset
  category: AMR Research
  description: Hyper-modular manifest structure with dedicated subdirectories and annotated assembly recipes.
  version: '1.8'
# !SECTION

# SECTION data schemas (data contract) definition
data_schemas:
  # SECTION - Pipeline dataset 1 - Summary Abromics pipeline
  Summary:
    info:
      category: "Globally pipeline Summary"
      sub_category: "Pipeline Summary"
    source:
      type: "local_tsv"
      path: "./assets/test_data/1_test_data_ST22_dummy/test_data_Summary_20260307_105756.tsv"
    input_fields: !include '1_test_data_ST22_dummy/input_fields/Summary_input_fields.yaml'
    wrangling: !include '1_test_data_ST22_dummy/wrangling/Summary_wrangling.yaml'
    output_fields: !include '1_test_data_ST22_dummy/output_fields/Summary_output_fields.yaml'
  # !SECTION

  # SECTION - Pipeline data set 2 - Summary Quality metrics Reads and Assembly
  Quality_metrics:
    info:
      category: "Quality Control"
      sub_category: "Summary Quality metrics Reads and Assembly"
    source:
      type: "local_tsv"
      path: "./assets/test_data/1_test_data_ST22_dummy/test_data_Quality_metrics_20260307_105756.tsv"
    # REVIEW : needs reformating
    input_fields: !include '1_test_data_ST22_dummy/input_fields/Quality_metrics_input_fields.yaml'
    # REVIEW : needs to be created
    wrangling: !include '1_test_data_ST22_dummy/wrangling/Quality_metrics_wrangling.yaml'
    output_fields: !include '1_test_data_ST22_dummy/output_fields/Quality_metrics_output_fields.yaml'


  # SECTION - Pipeline data set 2 - Detailed summary Abromics pipleine
  Detailed_summary:
    info:
      category: "Gene detection"
      sub_category: "AMR gene / predicted phenotype detection  - summary"
      comments: "Filtered by % identity > 90 and % overlap > 85 Reason and legnth ratio > 0.8 assume true values"
    source:
      type: "local_tsv"
      path: "./assets/test_data/1_test_data_ST22_dummy/test_data_Detailed_Summary_20260307_105756.tsv"

    # REVIEW : needs reformating
    input_fields: !include '1_test_data_ST22_dummy/input_fields/Detailed_summary_input_fields.yaml'
    # REVIEW : needs to be created
    # Separate the column HSP Length/Total Length into Length and Total Lenght using "/" as separator
    # Compute the length ratio: Length / Total Length
    # Filter % identity > 90 and % overlap > 85 Reason and legnth ratio > 0.8 assume true values
    # Group by sample_id 
    # For each isolate create a barplot where columns in x are predicted phenotype and the height the number of data type that supported the prediction (count 1 per method) 
    # Discards all the columns that are not needed for the plot
    # Needs to have facets and be able to scroll to see all the samples (2 or 3 columns, as many rows are necessary for all samples)
    wrangling: !include '1_test_data_ST22_dummy/wrangling/Detailed_summary_wrangling.yaml'
    # REVIEW : needs to be created
    output_fields: !include '1_test_data_ST22_dummy/output_fields/Detailed_summary_output_fields.yaml'

  # SECTION - Pipeline dataset 2 - FastP - Quality insurance
  FastP:
    info:
      category: "Quality Control"
      sub_category: "Reads Quality"
    source:
      type: "local_tsv"
      path: "./assets/test_data/1_test_data_ST22_dummy/test_data_FastP_20260307_105756.tsv"
    input_fields: !include '1_test_data_ST22_dummy/input_fields/FastP_input_fields.yaml'
    wrangling: !include '1_test_data_ST22_dummy/wrangling/FastP_wrangling.yaml'
    output_fields: !include '1_test_data_ST22_dummy/output_fields/FastP_output_fields.yaml'
  # !SECTION

  # SECTION - Pipeline dataset 3 - Quast - Quality insurance
  Quast:
    info:
      category: "Quality Control"
      sub_category: "Assembly Quality"
    source:
      type: "local_tsv"
      path: "./assets/test_data/1_test_data_ST22_dummy/test_data_Quast_20260307_105756.tsv"
    input_fields: !include '1_test_data_ST22_dummy/input_fields/Quast_input_fields.yaml'
    wrangling: !include '1_test_data_ST22_dummy/wrangling/Quast_wrangling.yaml'
    output_fields: !include '1_test_data_ST22_dummy/output_fields/Quast_output_fields.yaml'
  # !SECTION

  # SECTION - Pipeline dataset 4 - Bracken - Quality insurance - Taxonomic classification/contamination
  Bracken:
    info:
      category: "Quality Control"
      sub_category: "Reads Taxonomic classification"
    source:
      type: "local_tsv"
      path: "./assets/test_data/1_test_data_ST22_dummy/test_data_Bracken_20260307_105756.tsv"
    input_fields: !include '1_test_data_ST22_dummy/input_fields/Bracken_input_fields.yaml'
    wrangling: !include '1_test_data_ST22_dummy/wrangling/Bracken_wrangling.yaml'
    output_fields: !include '1_test_data_ST22_dummy/output_fields/Bracken_output_fields.yaml'
  # !SECTION

  # SECTION - Pipeline dataset 5 - ResFinder - AMR detection
  ResFinder:
    info:
      category: "Gene detection"
      sub_category: "AMR gene detection"
    source:
      type: "local_tsv"
      path: "./assets/test_data/1_test_data_ST22_dummy/test_data_ResFinder_20260307_105756.tsv"
    input_fields: !include '1_test_data_ST22_dummy/input_fields/ResFinder_input_fields.yaml'
    wrangling: !include '1_test_data_ST22_dummy/wrangling/ResFinder_wrangling.yaml'
    output_fields: !include '1_test_data_ST22_dummy/output_fields/ResFinder_output_fields.yaml'
  # !SECTION

  # SECTION - Pipeline dataset 6 - MLST - Multilocus sequence typing
  MLST:
    info:
      category: "Strain Classification"
      sub_category: "Multilocus Typing"
    source:
      type: "local_tsv"
      path: "./assets/test_data/1_test_data_ST22_dummy/test_data_MLST_results_20260307_105756.tsv"
    input_fields: !include '1_test_data_ST22_dummy/input_fields/MLST_input_fields.yaml'
    wrangling: !include '1_test_data_ST22_dummy/wrangling/MLST_wrangling.yaml'
    output_fields: !include '1_test_data_ST22_dummy/output_fields/MLST_output_fields.yaml'
  # !SECTION
# !SECTION

# SECTION - Additional datasets schemas
additional_datasets_schemas:
  # SECTION - Additional dataset 1 - VirulenceFinder - Virulence genes detection
  VirulenceFinder:
    info:
      category: "Gene detection"
      sub_category: "VirulenceFinder"
    source:
      type: "local_tsv"
      path: "./assets/test_data/2_VIGAS-P_ST22_dummy/test_data_VIGAS_VirulenceFinder_20260307_105756.tsv"
    input_fields: !include '1_test_data_ST22_dummy/input_fields/VirulenceFinder_input_fields.yaml'
    wrangling: !include '1_test_data_ST22_dummy/wrangling/VirulenceFinder_wrangling.yaml'
    output_fields: !include '1_test_data_ST22_dummy/output_fields/VirulenceFinder_output_fields.yaml'
  # !SECTION

  # SECTION - Additional dataset 2 - APEC_STEC_virulence_genes: Reference dataset
  APEC_STEC_virulence_genes:
    info:
      category: "Gene detection"
      sub_category: "VirulenceFinder Reference dataset"
      comments: "Virulence types of interest for STEC"
    source:
      type: "local_tsv"
      path: "./assets/ref_data/Virulence_genes_APEC/Virulence_genes_APEC.tsv"
    input_fields: !include '../../../assets/ref_data/Virulence_genes_APEC/Virulence_genes_APEC_input_fields.yaml'
    wrangling:
      - action: "strip_whitespace"
    output_fields: [ ]
  # !SECTION
# !SECTION

# SECTION - Metadata schema
metadata_schema:
  info:
    category: "Metadata"
    sub_category: "Metadata"
  source:
    type: "local_tsv"
    path: "./assets/test_data/1_test_data_ST22_dummy/test_metadata_20260307_105756.tsv"
  input_fields: !include './1_test_data_ST22_dummy/input_fields/metadata_schema_input_fields.yaml'
  wrangling: !include './1_test_data_ST22_dummy/wrangling/metadata_schema_wrangling.yaml'
  output_fields: !include './1_test_data_ST22_dummy/output_fields/metadata_schema_output_fields.yaml'
# !SECTION

# SECTION - Tier 1 Assembly + Tier 2 Assembly
assembly_manifests:
  # SECTION - Tier 1 & 2 Assembly: Individual joins for analysis (Agnostic Pillar)
  FastP_with_metadata:
    ingredients:
      - dataset_id: "FastP"
      - dataset_id: "metadata_schema"
    recipe: !include '1_test_data_ST22_dummy/wrangling/FastP_Metadata_wrangling.yaml'
  Quast_with_metadata:
    ingredients:
      - dataset_id: "Quast"
      - dataset_id: "metadata_schema"
    recipe: !include '1_test_data_ST22_dummy/wrangling/Quast_Metadata_wrangling.yaml'
  Bracken_with_metadata:
    ingredients:
      - dataset_id: "Bracken"
      - dataset_id: "metadata_schema"
    recipe: !include '1_test_data_ST22_dummy/wrangling/Bracken_Metadata_wrangling.yaml'
  ResFinder_with_metadata:
    ingredients:
      - dataset_id: "ResFinder"
      - dataset_id: "metadata_schema"
    recipe: !include '1_test_data_ST22_dummy/wrangling/ResFinder_Metadata_wrangling.yaml'
  MLST_with_metadata:
    ingredients:
      - dataset_id: "MLST"
      - dataset_id: "metadata_schema"
    recipe: !include '1_test_data_ST22_dummy/wrangling/MLST_Metadata_wrangling.yaml'
  QC_Reads_Anchor:
    ingredients:
      - dataset_id: "FastP"
      - dataset_id: "Quast"
      - dataset_id: "Bracken"
      - dataset_id: "metadata_schema"
    recipe: !include '1_test_data_ST22_dummy/wrangling/QC_Reads_Anchor_wrangling.yaml'


  # !SECTION

  # SECTION - Tier 1 & 2 Assembly: Master Cross-Dataset Integration
  ST22_Anchor:
    description: "Primary joined dataset for ST22 Dummy analysis."
    ingredients:
      - dataset_id: "metadata_schema"
      - dataset_id: "FastP"
      - dataset_id: "ResFinder"
      - dataset_id: "MLST"
      - dataset_id: "VirulenceFinder"
      - dataset_id: "APEC_STEC_virulence_genes"
    recipe: !include '1_test_data_ST22_dummy/wrangling/ST22_Anchor_wrangling.yaml'
    final_contract: !include '1_test_data_ST22_dummy/output_fields/ST22_Anchor_final_output_fields.yaml'
  # !SECTION
# !SECTION

# !SECTION

# SECTION - UI Classification (Tabs)
analysis_groups:
  # SECTION - Analysis group 1 - Quality Control
  Quality Control:
    description: "📊 Quality Control"
    plots:
      # SECTION - plot qc 1 - Reads quality
      qc_reads_horizontal_barplot:
        info: "Provides a distribution of total reads per sample by taxonomy proportion."
        spec: !include '1_test_data_ST22_dummy/plots/FastP_reads_horizontal_barplot.yaml'
      # !SECTION

      # SECTION - plot qc 2 - Assembly quality
      assembly_quality_dotplot:
        info: "Provides a distribution of assembly quality metrics per sample."
        spec: !include '1_test_data_ST22_dummy/plots/Quast_assembly_quality_barplot.yaml'
      # !SECTION
  # !SECTION

  # SECTION - Analysis group 2 - Results
  Results:
    description: "💊 AMR and ☠️ Virulence"
    plots:
      # SECTION - plot results 1 - Heatmap - AMR (Resfinder + Metadata)
      amr_heatmap:
        info: "Heatmap showing AMR gene presence across samples."
        spec: !include '1_test_data_ST22_dummy/plots/ResFinder_genes_heatmap.yaml'
      # !SECTION

      # SECTION - plot results 2 - Bar chart - Virulence
      virulence_bar:
        info: "Bar chart counting selected virulence genes."
        spec: !include '1_test_data_ST22_dummy/plots/VirulenceFinder_counts_bar.yaml'
      # !SECTION

      # SECTION - plot results 3 - Bar chart - MLST + Metadata
      mlst_bar:
        info: "Bar chart showing frequency of sequence types by territory."
        spec: !include '1_test_data_ST22_dummy/plots/MLST_counts_bar.yaml'
      # !SECTION

      # SECTION - plot results 4 - Integration plot (Master classification)
      virulence_variants:
        info: "Integration plot showing AMR + Virulence + MLST."
        spec: !include '1_test_data_ST22_dummy/plots/integration_plot.yaml'
      # !SECTION
  # !SECTION
# !SECTION

# SECTION - Plot defaults
plot_defaults:
  height: 450
  theme: theme_minimal
  show_legend: true
# !SECTION
