id: ST22_single
type: species
data_schemas:
  Summary:
    input_fields:
      sample_id: {original_name: "sample_id", type: numeric, is_primary_key: true}
  FastP:
    input_fields:
      sample_id: {original_name: "sample_id", type: numeric, is_primary_key: true}
      total_reads: {original_name: "total_reads", type: numeric}

assembly_manifests:
  ST22_Anchor:
    recipe:
      - action: join
        right_ingredient: FastP
        on: sample_id
