sample_id:
  original_name: sample_id
  type: categorical
  label: Sample Id
  is_primary_key: true
quality_module:
  original_name: Quality_Module
  type: categorical
  label: Quality Module
quality_feedback:
  original_name: Quality_Feedback
  type: categorical
  label: Quality Feedback
total_reads_after:
  original_name: total_reads_after
  type: numeric
  label: Total Reads After
ratio_reads_after:
  original_name: ratio_reads_after
  type: numeric
  label: Ratio Reads After
bracken_main_taxon:
  original_name: bracken_main_taxon
  type: categorical
  label: Bracken Main Taxon
proportion_of_main_taxon:
  original_name: proportion_of_main_taxon
  type: numeric
  label: Proportion Of Main Taxon
reads_gc_content:
  original_name: reads_gc_content
  type: numeric
  label: Reads Gc Content
n50:
  original_name: N50
  type: numeric
  label: N50
total_length:
  original_name: Total_length
  type: numeric
  label: Total Length
largest_contig:
  original_name: Largest_contig
  type: numeric
  label: Largest Contig
num_contigs_500bp:
  original_name: num_contigs_500bp
  type: numeric
  label: Num Contigs 500Bp
num_contigs_0bp:
  original_name: num_contigs_0bp
  type: numeric
  label: Num Contigs 0Bp
