output_fields:
  sample_id:
    original_name: sample_id
    type: numeric
    label: Sample Id
    is_primary_key: true
  Source:
    original_name: Source
    type: categorical
    label: Source
  Year:
    original_name: Year
    type: numeric
    label: Year
  Country:
    original_name: Country
    type: categorical
    label: Country
  Sequence Type:
    original_name: Sequence Type
    type: categorical
    label: "MLST Sequence Type"
  serotypefinder_serotype:
    original_name: serotypefinder_serotype
    type: categorical
    label: Serotype
  Selected_Virulence_Genes:
    original_name: VF_gene
    type: categorical
    label: Gene (VirulenceFinder)
  VF_protein:
    original_name: VF_protein
    type: categorical
    label: Protein (VirulenceFinder)
