sample_id:
  original_name: sample_id
  type: numeric
  label: Sample Id
  is_primary_key: true
source:
  original_name: Source
  type: categorical
  label: Source
  mandatory: false
year:
  original_name: Year
  type: numeric
  label: Year
  mandatory: false
country:
  original_name: Country
  type: categorical
  label: Country
  mandatory: false
