input_fields:
  sample_id:
    original_name: "sample_id"
    type: numeric
    is_primary_key: true
  total_reads:
    original_name: "total_reads"
    type: numeric
  q30_rate:
    original_name: "q30_rate"
    type: numeric
  gc_content:
    original_name: "gc_content"
    type: numeric

output_fields:
  sample_id:
    type: numeric
  total_reads:
    type: numeric
  q30_rate:
    type: numeric
  gc_content:
    type: numeric
