input_fields:
  sample_id:
    original_name: "sample_id"
    type: numeric
    is_primary_key: true
  scheme:
    original_name: "Scheme"
    type: categorical
  sequence_type:
    original_name: "Sequence Type"
    type: categorical

output_fields:
  sample_id:
    type: numeric
  scheme:
    type: categorical
  sequence_type:
    type: categorical
