input_fields:
  sample_id:
    type: categorical
    role: foreign_key
    original_name: sample_id
    label: Sample ID
  gene:
    type: categorical
    original_name: Gene
    label: Gene name
  predicted_phenotype:
    type: categorical
    original_name: Predicted Phenotype
    label: Predicted Phenotype
  identity:
    type: numeric
    original_name: '%Identity'
    label: Sequence Identity
  overlap:
    type: numeric
    original_name: '%Overlap'
    label: Sequence Overlap
  accession:
    type: categorical
    original_name: Accession
    label: NCBI Accession
