input_fields:
  sample_id:
    type: categorical
    role: primary_key
    original_name: sample_id
    label: Sample ID
  Source:
    type: categorical
    original_name: Source
    label: Biological Source
  Year:
    type: numeric
    original_name: Year
    label: Sampling Year
  Country:
    type: categorical
    original_name: Country
    label: Country of Origin
