input_fields:
  sample_id:
    original_name: "sample_id"
    type: numeric
    is_primary_key: true
  taxon_1:
    original_name: "taxon_1"
    type: categorical
  proportion_1:
    original_name: "proportion_1"
    type: numeric

output_fields:
  sample_id:
    type: numeric
  taxon_1:
    type: categorical
  proportion_1:
    type: numeric
