%% TODO - needs to be revised when this becomes more clear - and updated to correspond to the text description
graph TD
    subgraph Ext ["External World"]
        Galaxy["Galaxy/IRIDA History"]
        API["API eg. BioBlend, .csv"]
    end


    subgraph "The Dashboard (Shiny for Python)"
        direction TB
        
        %% TODO- need to integrate relations with config layer
        subgraph "Ingress & Prep"
            direction TB 
            
            Connector["
            <b><u>Connection Layer</u></b>
            CONNECTOR: 
            fetches raw data"]
            
            Ingest["
            <b><u>Ingestion Layer</u></b>
            INGRESS: 
            reads files
            validates schema
            ensures data integrity"]

            Wrangler["
            <b><u>Data Wrangling Layer</u></b>
            TRANSFORMER:
            Converts raw data to 
            TIDY data contract"]
        end

        subgraph "<u>Configuration Layer</u>"
            DataRules["<b><u>Data Rules</u><b>
            + Visualisation defaults
            + Minimum metadata format
            species_config.yaml"]
            UIPrefs["<b>UI Preferences</b><br/>(user_prefs.yaml)"]
            %% SystemEnv["<b>Environment Config</b><br/>(secrets.env / paths.yaml)"]
        end


        subgraph "<u>Orchestrator</u>"
            Logic{{"<b>Server</b><br/>
            Coordinates dataflow, user input"}}
        end

        subgraph "Presentation"
            Factory[<b><u>Visualization Factory</u></b><br/>viz_core.py]
            UI[<b><u>Display & Interaction</u></b><br/>app.py UI]
        end
    
    end

    %% Data Flow
    Galaxy -->|Raw Files| API
    API -->|Auth/Stream| Connector
    Connector --> Ingest
    Ingest -->|Validated Data| Wrangler
    DataRules --> Ingest
    Wrangler -->|Tidy Data Contract| Logic
    
    DataRules -.->|Species Metadata| Logic
    Logic -->|Filtered Data| Factory
    Factory -->|Plotly Object| UI
    UI -->|User Inputs| Logic

    %% Styling
    style Ext fill:#b2e0f0,stroke:#b2e0f0,stroke-width:2px