%% TODO - needs to be revised when this becomes more clear - and updated to correspond to the text description
graph TD
    subgraph Ext ["External World"]
        Galaxy["Galaxy/IRIDA History"]
        API["API eg. BioBlend, .csv"]
    end


    subgraph "The Dashboard (Shiny for Python)"
        direction TB
        
        %% TODO- need to integrate relations with config layer
        subgraph "Ingress & Prep"
            direction TB 
            
            Connector["<b><u>Connection Layer</u></b><br/>CONNECTOR:<br/>fetches raw data"]
            
            Ingest["<b><u>Ingestion Layer</u></b><br/>INGESTION:<br/>reads files<br/>validates schema<br/>ensures data integrity"]

            Wrangler["<b><u>Data Wrangling Layer</u></b><br/>TRANSFORMER:<br/>Converts raw data to<br/>TIDY data contract"]
        end

        subgraph "<u>Configuration Layer</u>"
            DataRules["<b><u>Data Rules</u></b><br/>+ Visualisation defaults<br/>+ <b>Data contracts</b><br/>eg. species_config.yaml"]
            UIPrefs["<b>UI Preferences</b><br/>User preferences overwrite<br/>eg user_prefs.yaml"]
            %% SystemEnv["<b>Environment Config</b><br/>(secrets.env / paths.yaml)"]
        end


        subgraph "<u>Controller</u>"
            Logic{{"<b><u>Server part 1<br/>server.py</u></b><br/>Coordinates dataflow<br/>user input"}}
        end

        subgraph "Presentation"
            Factory["<b><u>Visualization Factory</u></b>"]
            UI["<b><u>Server part 2:<br/>ui.py</u></b><br/>Display & Interaction"]
        end
    
    end

    %% Data Flow
    Galaxy -->|Raw Files| API
    API -->|Auth/Stream| Connector
    Connector --> Ingest
    Ingest -->|Validated Data| Wrangler
    DataRules --> Ingest
    Wrangler -->|Tidy Data Contract| Logic
    
    DataRules -.->|Species Metadata| Logic
    Logic -->|Filtered Data| Factory
    Factory -->|Plotly Object| UI
    UI -->|User Inputs| Logic

    %% Styling
    style Ext fill:#b2e0f0,stroke:#b2e0f0,stroke-width:2px