spec:
  factory_id: bar_logic
  target_dataset: AMR_Profile_Joint
  x: Year
  fill: Multiresistant
  facet_by: Country
  position: dodge
  theme: theme_light
  labels:
    title: "Multi-Resistance by Country"
    fill: "Multiresistant"
