output_fields:
  sample_id:
    type: categorical
    label: Sample ID
    is_primary_key: true
    original_name: sample_id
  source:
    type: categorical
    label: Biological Source
    original_name: source
  year:
    type: numeric
    label: Collection Year
    original_name: year
  country:
    type: categorical
    label: Origin Country
    original_name: country
  sequence_type:
    type: categorical
    label: MLST Sequence Type
    original_name: sequence_type
  serotype:
    type: categorical
    label: Serotype
    original_name: serotype
  selected_virulence_genes:
    type: categorical
    label: Gene (VirulenceFinder)
    original_name: selected_virulence_genes
  vf_protein:
    type: categorical
    label: Protein (VirulenceFinder)
    original_name: vf_protein
