output_fields:
  sample_id:
    label: Sample ID
    original_name: sample_id
    type: categorical
  predicted_phenotype:
    label: Predicted Phenotype
    original_name: predicted_phenotype
    type: categorical
  data_type:
    label: Data Type
    original_name: data_type
    type: categorical
  identity:
    label: '%Identity'
    original_name: identity
    type: categorical
  overlap:
    label: '%Overlap'
    original_name: overlap
    type: categorical
  length_ratio:
    label: Length Ratio
    original_name: length_ratio
    type: categorical
  source:
    label: Sample Source
    original_name: source
    type: categorical
  country:
    label: Country
    original_name: country
    type: categorical
  year:
    label: Year
    original_name: year
    type: categorical
