output_fields:
  sample_id:
    label: Sample ID
    original_name: sample_id
    type: categorical
  quality_module:
    label: Quality Module
    original_name: quality_module
    type: categorical
  quality_feedback:
    label: Quality Feedback
    original_name: quality_feedback
    type: categorical
  total_reads_after:
    label: Total Reads After
    original_name: total_reads_after
    type: categorical
  ratio_reads_after:
    label: Ratio Reads After
    original_name: ratio_reads_after
    type: categorical
  bracken_main_taxon:
    label: Bracken Main Taxon
    original_name: bracken_main_taxon
    type: categorical
  proportion_of_main_taxon:
    label: Proportion Of Main Taxon
    original_name: proportion_of_main_taxon
    type: categorical
  n50:
    label: N50
    original_name: n50
    type: categorical
  total_length:
    label: Total Length
    original_name: total_length
    type: categorical
