# NOTE This file is your **Contract Gatekeeper**. 
# It defines the "Which" (filtering) and the 
# "How" (final data types for Polars).
# keeping the label in output_fields is the "Safest" path. 
# It ensures that the human-readable name is explicitly bound to the final published version of that data
# regardless of how many joins or transformations it went through.

# output_fields:
# Standard selection (uses type from input_fields)
sample_id: {}
  # The fields definition is taken from input_fields
  # ok to use when nothing is changed
ST: {}
# Category now contains the name of the column that was unpivoted
category: 
  type: categorical
  label: "Feature Category"
# value now contains the value of the column that was unpivoted
value: 
  type: categorical
  label: "Feature Value"
# Mirrored table for quality control values - they are dropped in this

