sample_id:
  original_name: sample_id
  type: numeric
  label: Sample Id
  is_primary_key: true
VF_gene:
  original_name: VF_gene
  type: categorical
  label: Gene (VirulenceFinder)
VF_protein:
  original_name: VF_protein
  type: categorical
  label: Protein (VirulenceFinder)
# Results is long format - unique rows (so duplicated finding eg if several genes
# is now one row per gene - Format ok for downstream analysis )
