sample_id:
  original_name: sample_id
  type: numeric
  label: Sample Id
  is_primary_key: true
modified_date:
  original_name: modified_date
  type: categorical
  label: Modified Date
created_date:
  original_name: created_date
  type: categorical
  label: Created Date
metadata_healthy_diseased:
  original_name: metadata_healthy_diseased
  type: categorical
  label: Metadata Healthy Diseased
metadata_hensikt:
  original_name: metadata_hensikt
  type: categorical
  label: Metadata Hensikt
metadata_isolation_method:
  original_name: metadata_isolation_method
  type: categorical
  label: Metadata Isolation Method
metadata_research_project:
  original_name: metadata_research_project
  type: categorical
  label: Metadata Research Project
metadata_sample_material:
  original_name: metadata_sample_material
  type: categorical
  label: Metadata Sample Material
metadata_sequencer:
  original_name: metadata_sequencer
  type: categorical
  label: Metadata Sequencer
metadata_source:
  original_name: metadata_source
  type: categorical
  label: Metadata Source
mlst_scheme:
  original_name: mlst_scheme
  type: categorical
  label: Mlst Scheme
mlst_sequence_type:
  original_name: mlst_sequence_type
  type: categorical
  label: Mlst Sequence Type
reads_qc_coverage:
  original_name: reads_qc_coverage
  type: numeric
  label: Reads Qc Coverage
reads_qc_gc_content:
  original_name: reads_qc_gc_content
  type: numeric
  label: Reads Qc Gc Content
reads_qc_mean_phredscore:
  original_name: reads_qc_mean_phredscore
  type: numeric
  label: Reads Qc Mean Phredscore
reads_qc_proportionofmappedreads:
  original_name: reads_qc_proportionofmappedreads
  type: numeric
  label: Reads Qc Proportionofmappedreads
reads_qc_readlength:
  original_name: reads_qc_readlength
  type: numeric
  label: Reads Qc Readlength
reads_qc_speciesname:
  original_name: reads_qc_speciesname
  type: categorical
  label: Reads Qc Speciesname
readsqc_1_0_0_coverage:
  original_name: readsqc_1_0_0_coverage
  type: numeric
  label: Readsqc 1 0 0 Coverage
readsqc_1_0_0_gc_content:
  original_name: readsqc_1_0_0_gc_content
  type: numeric
  label: Readsqc 1 0 0 Gc Content
readsqc_1_0_0_mean_phredscore:
  original_name: readsqc_1_0_0_mean_phredscore
  type: numeric
  label: Readsqc 1 0 0 Mean Phredscore
readsqc_1_0_0_proportionofmappedreads:
  original_name: readsqc_1_0_0_proportionofmappedreads
  type: numeric
  label: Readsqc 1 0 0 Proportionofmappedreads
readsqc_1_0_0_readlength:
  original_name: readsqc_1_0_0_readlength
  type: numeric
  label: Readsqc 1 0 0 Readlength
readsqc_1_0_0_speciesname:
  original_name: readsqc_1_0_0_speciesname
  type: categorical
  label: Readsqc 1 0 0 Speciesname
respointfinder_pointfinder_mutations:
  original_name: respointfinder_pointfinder_mutations
  type: categorical
  label: Respointfinder Pointfinder Mutations
respointfinder_pointfinder_phenotypes:
  original_name: respointfinder_pointfinder_phenotypes
  type: categorical
  label: Respointfinder Pointfinder Phenotypes
respointfinder_resfinder_genes:
  original_name: respointfinder_resfinder_genes
  type: categorical
  label: Respointfinder Resfinder Genes
respointfinder_resfinder_phenotypes:
  original_name: respointfinder_resfinder_phenotypes
  type: categorical
  label: Respointfinder Resfinder Phenotypes
rpf2305_pointfinder_mutations:
  original_name: rpf2305_pointfinder_mutations
  type: categorical
  label: Rpf2305 Pointfinder Mutations
rpf2305_pointfinder_phenotypes:
  original_name: rpf2305_pointfinder_phenotypes
  type: categorical
  label: Rpf2305 Pointfinder Phenotypes
rpf2305_resfinder_genes:
  original_name: rpf2305_resfinder_genes
  type: categorical
  label: Rpf2305 Resfinder Genes
rpf2305_resfinder_phenotypes:
  original_name: rpf2305_resfinder_phenotypes
  type: categorical
  label: Rpf2305 Resfinder Phenotypes
rpf2403_disinfinder_genes:
  original_name: rpf2403_disinfinder_genes
  type: categorical
  label: Rpf2403 Disinfinder Genes
rpf2403_disinfinder_phenotypes:
  original_name: rpf2403_disinfinder_phenotypes
  type: categorical
  label: Rpf2403 Disinfinder Phenotypes
rpf2403_pointfinder_mutations:
  original_name: rpf2403_pointfinder_mutations
  type: categorical
  label: Rpf2403 Pointfinder Mutations
rpf2403_pointfinder_phenotypes:
  original_name: rpf2403_pointfinder_phenotypes
  type: categorical
  label: Rpf2403 Pointfinder Phenotypes
rpf2403_resfinder_genes:
  original_name: rpf2403_resfinder_genes
  type: categorical
  label: Rpf2403 Resfinder Genes
rpf2403_resfinder_phenotypes:
  original_name: rpf2403_resfinder_phenotypes
  type: categorical
  label: Rpf2403 Resfinder Phenotypes
serotypefinder_serotype:
  original_name: serotypefinder_serotype
  type: categorical
  label: Serotypefinder Serotype
virulence_finder_virulencegenes_proteinname:
  original_name: virulence_finder_virulencegenes_proteinname
  type: categorical
  label: Virulence Finder Virulencegenes Proteinname
