
# Define your Polars wrangling steps here
# Example for VIGAS-P wrangling
# - action: "derive_categories"
#   source_column: "cge_predicted_phenotype"
#   target_column: "AMR_Categories_Summary"      
#   separator: ", "
#   reference_file: "/home/evezeyl/Documents/Insync/gdrive/OBSWORK/20_GITS/SPARMVET_VIZ/config/references/amr_phenotypes/test_amr_categories_phenotype.tsv"
#   lookup_left: "cge_predicted_phenotype"
#   lookup_right: "Predicted Phenotype"
#   extract_column: "AMR Category (Class)"

- action: "keep_columns"
  target_column: ["sample_id","virulence_finder_virulencegenes_proteinname"]
- action: "split_and_explode"
  target_column: "virulence_finder_virulencegenes_proteinname"
  separator: ","
- action: "strip_whitespace"
- action: "split_and_explode"
  target_column: "virulence_finder_virulencegenes_proteinname"
  separator: ","
- action: "strip_whitespace"
- action: "split_column"
  source: "virulence_finder_virulencegenes_proteinname"
  new_columns: ["VF_gene", "VF_protein"]
  delimiter: ": "
  drop_source: true
- action: "strip_whitespace" 
- action: "unique_rows"
