id: VIGAS_VirulenceFinder
type: pipeline
info:
  display_name: Virulence Finder
  category: Edited
  tags:
  - VIGAS-P
  - STEC
  - Escherichia coli
  description: Manifest for Virulence Finder. Usable for STEC / E.coli.
  version: '1.0'
data_schemas:
  VIGAS_VirulenceFinder:
    input_fields: !include 'VIGAS_VirulenceFinder/VIGAS_VirulenceFinder_input_fields.yaml'
    wrangling: !include 'VIGAS_VirulenceFinder/VIGAS_VirulenceFinder_wrangling.yaml'
    output_fields: !include 'VIGAS_VirulenceFinder/VIGAS_VirulenceFinder_output_fields.yaml'
# plot_defaults:
#   height: 450
#   theme: theme_minimal
#   show_legend: true
# analysis_groups:
#   Example_Group:
#     description: Auto-scaffolded plotting group
#     plots:
#       demo_bar:
#         factory_id: bar_logic
#         target_dataset: VIGAS_VirulenceFinder
#         target_col: Replace_Me
#         title: Replace Me Title